<template>
  <div class="main">
    <div class="section header">
      <div class="title"><img class="fire-icon" src="/fire_sm.png">FIRE</div>
      <div class="subtitle">
        <!-- A Dataset for<br> -->
        <!-- <span class="uns">F</span>eedback <span class="uns">I</span>ntegration and -->
        <!-- <span class="uns">R</span>efinement <span class="uns">E</span>valuation -->
        <!-- <br>of Multimodal Models -->
        A Dataset for
        <span class="uns">F</span>eedback <span class="uns">I</span>ntegration and
        <br><span class="uns">R</span>efinement <span class="uns">E</span>valuation
        of Multimodal Models
      </div>
      <div class="author-list">
        <span class="author">
          <el-link href="#">Pengxiang Li</el-link>
          <span class="ind">&#9733;1,2</span>,
        </span>
        <span class="author">
          <el-link href="#">Zhi Gao</el-link>
          <span class="ind">&#9733;2,3</span>,
        </span>
        <span class="author">
          <el-link href="#">Bofei Zhang</el-link>
          <span class="ind">&#9733;2</span>,
        </span>
        <span class="author">
          <el-link href="#">Tao Yuan</el-link>
          <span class="ind">2</span>,
        </span>
        <span class="author">
          <el-link href="#">Yuwei Wu</el-link>
          <span class="ind">&#9993;1</span>,
        </span>
        <br>
        <span class="author">
          <el-link href="#">Mehrtash Harand</el-link>
          <span class="ind">4</span>,
        </span>
        <span class="author">
          <el-link href="#">Yunde Ji</el-link>
          <span class="ind">1</span>,
        </span>
        <span class="author">
          <el-link href="#">Song-Chun Zhu</el-link>
          <span class="ind">2,3,5</span>,
        </span>
        <span class="author">
          <el-link href="#">Qing Li</el-link>
          <span class="ind">&#9993;2</span>
        </span>
      </div>
      <div class="author-list">
        <span class="org">
          <span class="ind">1</span>
          Beijing Institute of Technology
        </span>
        <span class="org">
          <span class="ind">2</span>
          Beijing Institute for Artificial General Intelligence
        </span>
        <br>
        <span class="org">
          <span class="ind">3</span>
          Peking University
        </span>
        <span class="org">
          <span class="ind">4</span>
          Monash University
        </span>
        <span class="org">
          <span class="ind">5</span>
          Tsinghua University
        </span>
      </div>
    </div>
    <div class="section">
      <el-card class="teaser">
        <el-image src="./teaser.webp"></el-image>
      </el-card>
    </div>
    <div class="section">
      <div class="section-title">Introduction</div>
      <p class="intro">Vision language models (VLMs) have achieved impressive progress in diverse applications, becoming a prevalent
        research direction. In this paper, we build FIRE, a feedback-refinement dataset, consisting of 1.1M multi-turn
        conversations that are derived from 27 source datasets, empowering VLMs to spontaneously refine their responses
        based on user feedback across diverse tasks. To scale up the data collection, FIRE is collected in two
        components: FIRE-100K and FIRE-1M, where FIRE-100K is generated by GPT-4V, and FIRE-1M is freely generated via
        models trained on FIRE-100K. Then, we build FIRE-Bench, a benchmark to comprehensively evaluate the
        feedback-refining capability of VLMs, which contains 11K feedback-refinement conversations as the test data, two
        evaluation settings, and a model to provide feedback for VLMs. We develop the FIRE-LLaVA model by fine-tuning
        LLaVA on FIRE-100K and FIRE-1M, which shows remarkable feedback-refining capability on FIRE-Bench and
        outperforms untrained VLMs by 50%, making more efficient user-agent interactions and underscoring the
        significance of the FIRE dataset.</p>
    </div>
    <div class="section">
      <div class="section-title">Statistics</div>
      <el-carousel :interval="8000" height="300px">
        <el-carousel-item>
          <el-image class="stats-img" src="./stats/piechart.webp"></el-image>
        </el-carousel-item>
        <el-carousel-item>
          <el-image class="stats-img" src="./stats/piechart.webp"></el-image>
        </el-carousel-item>
        <el-carousel-item>
          <el-image class="stats-img" src="./stats/piechart.webp"></el-image>
        </el-carousel-item>
      </el-carousel>
    </div>
    <div class="section">
      <div class="section-title">Examples</div>
    <el-carousel :interval="8000" type="card" height="1200px">
      <el-carousel-item v-for="d in dataset">
        <Dialog class="example-dialog" :data="d" />
      </el-carousel-item>
    </el-carousel>
      </div>
    </div>
    <div class="section">
      <div class="section-title">Evaluation</div>
      <el-carousel :interval="8000" height="300px">
        <el-carousel-item>
          <el-image class="stats-img" src="./eval1.webp"></el-image>
        </el-carousel-item>
        <el-carousel-item>
          <el-image class="stats-img" src="./eval1.webp"></el-image>
        </el-carousel-item>
        <el-carousel-item>
          <el-image class="stats-img" src="./eval1.webp"></el-image>
        </el-carousel-item>
      </el-carousel>
    </div>
    <div class="footer">
      This website is inspired by <el-link href="https://mathvista.github.io/">MathVista</el-link> and <el-link href="https://nerfies.github.io/">Nerfies</el-link>.
    </div>
</template>

<script setup>
import Dialog from './Dialog.vue'

import { onMounted, ref } from 'vue'

const dataset = ref([])

const loadData = async () => {
  const resp = await fetch('./data/demo.json')
  // dataset.value = resp.data
  dataset.value = await resp.json()
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.main {
  text-align: center;
  color: #333;
}

.header {
  margin: 60px 0 0 0 !important;
}

.title {
  font-size: 5em;
}

.subtitle {
  font-size: 2.5em;
  color: #555;
}

.author-list {
  margin-top: 20px;
}

.author a {
  font-size: 1.2em;
  font-weight: normal;
  color: #337ecc;
}

.org {
  margin: 0 4px 0 4px;
}

.ind {
  font-size: 0.8em;
  vertical-align: super;
}

.section {
  margin: 50px 0;
}

.section-title {
  margin: 20px;
  font-size: 2em;
  font-weight: bold;
}

.uns {
  text-decoration: underline;
}

.fire-icon {
  width: 0.8em;
  height: 0.8em;
  margin-right: 0.2em;
}

.teaser {
  max-width: 1280px;
  margin: 0 auto;
}

.stats-img {
  height: 300px;
}

.intro {
  text-align: left;
  font-size: 1em;
  line-height: 150%;
}

.example-dialog {
  width: 640px;
}

.footer {
  color: #aaa;
  margin: 100px 0 60px 0;
}
</style>
